/**
 * Main Entry Point: AI-Powered Safety-Aware Tourism Platform
 * Branch: safety-analyzer-testing
 * Purpose: Backend orchestration for ML-based safety analysis and vehicle recommendation.
 * Feature: Real-time Model Performance Monitoring from Saved Metrics
 */

const express = require("express");
const cors = require("cors");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

// --- 1. Import Routes ---
const safetyRoutes = require("./routes/safetyRoutes");

const app = express();

// --- 2. Middleware ---
app.use(cors());
app.use(express.json());

/**
 * --- 3. Model Performance Monitoring ---
 * Purpose: Reads the 'model_metrics.json' file generated by the Python training script.
 * This ensures the terminal displays the REAL R2 score and Error metrics 
 * calculated during the training phase.
 */
const displayModelMetrics = () => {
  const metricsPath = path.join(__dirname, "ai-engine", "scripts", "model_metrics.json");

  // Check if the metrics file exists
  if (fs.existsSync(metricsPath)) {
    try {
      const rawData = fs.readFileSync(metricsPath, "utf8");
      const metrics = JSON.parse(rawData);

      console.log("=================================================");
      console.log(`🎯 MACHINE LEARNING STATUS:`);
      console.log(`📈 Real Model Accuracy (R2 Score): ${metrics.accuracy}%`);
      console.log(`📉 Mean Absolute Error (MAE): ${metrics.mae}`);
      console.log(`📊 Trained Scenarios: ${metrics.sample_size}`);
      console.log(`✅ System is ready for validated safety recommendations.`);
      console.log("=================================================\n");
    } catch (err) {
      console.error("⚠️ Error parsing model metrics:", err.message);
    }
  } else {
    console.warn("⚠️ Warning: model_metrics.json not found.");
    console.log("👉 Please run 'python3 src/ai-engine/scripts/train_model.py' to generate metrics.\n");
  }
};

// --- 4. Base API Endpoint ---
app.get("/", (req, res) => {
  res.status(200).json({
    success: true,
    message: "Tourism Platform: Testing Branch (ML-Only) is Running! 🚀",
    status: "Healthy",
    branch: "safety-analyzer-testing",
    research_scope: "Real ML Inference + Geospatial Route Analysis",
    note: "Neo4j GraphRAG is excluded from this specific milestone branch.",
    endpoints: {
      safetyRecommendation: "/api/safety/recommend-vehicle",
    },
  });
});

// --- 5. API Routes ---
app.use("/api/safety", safetyRoutes);

// --- 6. Global Error Handler ---
app.use((err, req, res, next) => {
  console.error("TESTING_BRANCH_SERVER_ERROR:", err.stack);

  res.status(500).json({
    success: false,
    branch: "safety-analyzer-testing",
    message: "Internal Server Error in Testing Branch",
    error: err.message,
  });
});

// --- 7. Server Start ---
const PORT = process.env.PORT || 5001;

app.listen(PORT, () => {
  console.log("\n=================================================");
  console.log(`🚀 TESTING BRANCH is live on http://localhost:${PORT}`);
  console.log("🧠 Research Engine: Random Forest ML Active");
  console.log(`🔗 Main Endpoint: http://localhost:${PORT}/api/safety/recommend-vehicle`);
  
  // Display the real accuracy metrics on startup
  displayModelMetrics();
});