import React, { useState } from 'react';
import axios from 'axios';

const ItineraryManager = () => {
    const [preferences, setPreferences] = useState([]);
    const [maxTime, setMaxTime] = useState(150);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);

    const availablePreferences = ["Nature", "History", "Religious", "Adventure", "Shopping"];

    const handleCheckboxChange = (pref) => {
        if (preferences.includes(pref)) {
            setPreferences(preferences.filter(p => p !== pref));
        } else {
            setPreferences([...preferences, pref]);
        }
    };

    const handleOptimize = async () => {
        if (preferences.length === 0) {
            alert("Please select at least one preference");
            return;
        }

        setLoading(true);
        try {
            const response = await axios.post('http://localhost:8080/api/itinerary/optimize', {
                preferences: preferences,
                max_time_minutes: parseInt(maxTime),
                current_lat: 7.2906, 
                current_lon: 80.6337
            });
            setResult(response.data.data);
        } catch (error) {
            console.error("Optimization Error:", error);
            alert("Failed to fetch itinerary. Check if servers are running.");
        }
        setLoading(false);
    };

    return (
        <div style={{ padding: '20px', maxWidth: '800px', margin: 'auto', fontFamily: 'Arial, sans-serif' }}>
            <h2 style={{ color: '#2c3e50' }}>Context-Aware Itinerary Optimizer</h2>
            
            <div style={{ marginBottom: '20px', border: '1px solid #ddd', padding: '20px', borderRadius: '8px', backgroundColor: '#f9f9f9' }}>
                <h4 style={{ marginTop: '0' }}>Select Your Preferences</h4>
                <div style={{ display: 'flex', gap: '15px', flexWrap: 'wrap', marginBottom: '20px' }}>
                    {availablePreferences.map(pref => (
                        <label key={pref} style={{ cursor: 'pointer' }}>
                            <input 
                                type="checkbox" 
                                checked={preferences.includes(pref)}
                                onChange={() => handleCheckboxChange(pref)} 
                                style={{ marginRight: '5px' }}
                            /> {pref}
                        </label>
                    ))}
                </div>

                <div style={{ marginBottom: '20px' }}>
                    <label style={{ fontWeight: 'bold', marginRight: '10px' }}>Time Limit (minutes): </label>
                    <input 
                        type="number" 
                        value={maxTime} 
                        onChange={(e) => setMaxTime(e.target.value)} 
                        style={{ padding: '5px', width: '100px' }}
                    />
                </div>

                <button 
                    onClick={handleOptimize} 
                    disabled={loading}
                    style={{ 
                        padding: '10px 20px', 
                        cursor: loading ? 'not-allowed' : 'pointer', 
                        backgroundColor: '#007bff', 
                        color: 'white', 
                        border: 'none', 
                        borderRadius: '5px',
                        fontSize: '16px'
                    }}
                >
                    {loading ? 'Optimizing...' : 'Generate Itinerary'}
                </button>
            </div>

            {result && (
                <div style={{ border: '2px solid #28a745', padding: '20px', borderRadius: '8px', backgroundColor: '#e9f7ef' }}>
                    <h3 style={{ color: '#155724', marginTop: '0' }}>Your Spatio-Temporal Optimized Route</h3>
                    <p><strong>Estimated Time:</strong> {result.estimated_time_required}</p>
                    
                    <ul style={{ fontSize: '18px', lineHeight: '1.6' }}>
                        {result.optimized_route.map((place, index) => (
                            <li key={index}><strong>{index + 1}.</strong> {place}</li>
                        ))}
                    </ul>

                    <div style={{ backgroundColor: '#ffffff', padding: '15px', marginTop: '20px', borderLeft: '4px solid #17a2b8' }}>
                        <h4 style={{ marginTop: '0', color: '#17a2b8' }}>Sub-Objectives: AI Insights</h4>
                        <p style={{ fontStyle: 'italic', color: '#555' }}>
                            {result.ai_summary}
                        </p>
                        <small style={{ color: '#888' }}>Generated by XAI text-formatter</small>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ItineraryManager;